_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 3
                - 16
                - 23
                - 55
            "4": 3.10.11
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
batch_size:
    value: 2
epochs:
    value: 1
learning_rate:
    value: 0.0001
model:
    value: ViT-V-Net
optimizer:
    value: Adam
